### ISSUE TITLE
P9 cooler files appear to be corrupt.

### ISSUE THREAD

**Issue by lepidotos** [cwoffenden/talosmods#1]
I wasn't planning on also making this a ticket since I figured it's already on the RCS forums and I'd be annoyingly repetitive posting it here too but I figure it'd be good for issue tracking I suppose.
![uhh](https://github.com/user-attachments/assets/f95893e1-01c3-498e-86b8-4bfae6bc672d)
Freshly-redownloaded files won't open in any dwg-supporting medium, including BricsCAD itself.

**Comment by cwoffenden** [comment]
I used LFS for the files, did your Git client init LFS or do you just have a text file with the URL in instead of the DWG?

(I’ve not checked the RCS forums for a while, I really should)

**Comment by cwoffenden** [comment]
@lepidotos Adding to my earlier message, on first checkout the content of LFS files look like this:
```
version https://git-lfs.github.com/spec/v1
oid sha256:38ae7a931e8c4e6e32c037d0ab3110220c85bd861088de3ad4a0185db90ddfd1
size 181792
```
After you initialise LFS these text files are replaced with the content. It only needs doing once, the repository will work with the binary files afterwards:

![LFS](https://github.com/user-attachments/assets/085c1bfb-f851-465c-9682-ef3d966a6bad)

(This is with Fork as the Git client, others will have the same option)

**Comment by lepidotos** [comment]
Thanks, I probably should have checked that, I'll be more thorough next time.
